### ISSUE TITLE
Add Unit Testing

### ISSUE THREAD

**Issue by geoperez** [unosquare/pocodata#1]

**Comment by geoperez** [comment]
@JCorrea13 you can also continue with this branch.

**Comment by JCorrea13** [comment]
EOD: Working on this issue, first of all I will have to fix some FxCopAnalyzers and StyleCopissues.

**Comment by JCorrea13** [comment]
EOD: Still workin in fixing th issues from  FxCopAnalyzers and StyleCopissues.

**Comment by JCorrea13** [comment]
EOD: Working on adding test for insert operations. I have some problems on project references

**Comment by JCorrea13** [comment]
EOD: Working on basic operations tests

**Comment by JCorrea13** [comment]
EOD: I have been working on general test. Now I have created a base class to setup and clean every test. I will start adding TestClasses for each operation (select, insert, update, delete).

**Comment by JCorrea13** [comment]
EOD: I have been working on a clear approach to make test.

I have been having some problems bc of the test are being executed in parallel. I will configure the tests to run in a single thread. 

@geoperez  could you validate the approach I am using to perform the test? You could check the classses: 

-  [DbTest](https://github.com/unosquare/pocodata/blob/Issue1-1AddUnitTesting/Unosquare.PocoData.Tests/DbTest.cs) : base test class to setup and clean database

- [SelectTest](https://github.com/unosquare/pocodata/blob/Issue1-1AddUnitTesting/Unosquare.PocoData.Tests/SelectTest.cs): example using DbTest

**Comment by geoperez** [comment]
It's kinda OK, but I would recommend don't use the library to insert the data. Instead, probably run a SQL script with all the mock data.

**Comment by JCorrea13** [comment]
EOD: I am working on running an script instead of using the library to initlize tests.
